# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_world.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(409, 261)
        Dialog.setModal(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 385, 231))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.WorldPop = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.WorldPop.setMinimumSize(QtCore.QSize(200, 0))
        self.WorldPop.setObjectName("WorldPop")
        self.human = QtWidgets.QSpinBox(self.WorldPop)
        self.human.setGeometry(QtCore.QRect(140, 20, 42, 20))
        self.human.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.human.setMinimum(0)
        self.human.setMaximum(100)
        self.human.setSingleStep(1)
        self.human.setProperty("value", 1)
        self.human.setObjectName("human")
        self.computer = QtWidgets.QSpinBox(self.WorldPop)
        self.computer.setGeometry(QtCore.QRect(140, 60, 42, 22))
        self.computer.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.computer.setMinimum(0)
        self.computer.setMaximum(100)
        self.computer.setSingleStep(1)
        self.computer.setProperty("value", 3)
        self.computer.setObjectName("computer")
        self.heightLabel_3 = QtWidgets.QLabel(self.WorldPop)
        self.heightLabel_3.setGeometry(QtCore.QRect(30, 20, 91, 20))
        self.heightLabel_3.setObjectName("heightLabel_3")
        self.widthLabel_3 = QtWidgets.QLabel(self.WorldPop)
        self.widthLabel_3.setGeometry(QtCore.QRect(30, 60, 101, 20))
        self.widthLabel_3.setObjectName("widthLabel_3")
        self.widthLabel_4 = QtWidgets.QLabel(self.WorldPop)
        self.widthLabel_4.setGeometry(QtCore.QRect(30, 100, 91, 20))
        self.widthLabel_4.setObjectName("widthLabel_4")
        self.wild = QtWidgets.QSpinBox(self.WorldPop)
        self.wild.setGeometry(QtCore.QRect(140, 100, 42, 22))
        self.wild.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.wild.setMinimum(0)
        self.wild.setMaximum(100)
        self.wild.setSingleStep(1)
        self.wild.setProperty("value", 0)
        self.wild.setObjectName("wild")
        self.human.raise_()
        self.computer.raise_()
        self.heightLabel_3.raise_()
        self.widthLabel_3.raise_()
        self.widthLabel_4.raise_()
        self.wild.raise_()
        self.horizontalLayout_2.addWidget(self.WorldPop)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.worldSize = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.worldSize.setMinimumSize(QtCore.QSize(150, 0))
        self.worldSize.setMaximumSize(QtCore.QSize(186, 16777215))
        self.worldSize.setObjectName("worldSize")
        self.height = QtWidgets.QSpinBox(self.worldSize)
        self.height.setGeometry(QtCore.QRect(100, 20, 42, 20))
        self.height.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.height.setMinimum(5)
        self.height.setMaximum(999)
        self.height.setSingleStep(5)
        self.height.setProperty("value", 30)
        self.height.setObjectName("height")
        self.width = QtWidgets.QSpinBox(self.worldSize)
        self.width.setGeometry(QtCore.QRect(100, 60, 42, 22))
        self.width.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.width.setMinimum(5)
        self.width.setMaximum(999)
        self.width.setSingleStep(5)
        self.width.setProperty("value", 30)
        self.width.setObjectName("width")
        self.heightLabel = QtWidgets.QLabel(self.worldSize)
        self.heightLabel.setGeometry(QtCore.QRect(40, 20, 47, 20))
        self.heightLabel.setObjectName("heightLabel")
        self.widthLabel = QtWidgets.QLabel(self.worldSize)
        self.widthLabel.setGeometry(QtCore.QRect(40, 60, 47, 20))
        self.widthLabel.setObjectName("widthLabel")
        self.horizontalLayout_2.addWidget(self.worldSize)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.WorldPop.setTitle(_translate("Dialog", "World Population"))
        self.heightLabel_3.setText(_translate("Dialog", "Human Controlled"))
        self.widthLabel_3.setText(_translate("Dialog", "Computer Controlled"))
        self.widthLabel_4.setText(_translate("Dialog", "Wild (no rules)"))
        self.worldSize.setTitle(_translate("Dialog", "World Size"))
        self.heightLabel.setText(_translate("Dialog", "Height"))
        self.widthLabel.setText(_translate("Dialog", "Width"))

